### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by voldien** [voldien/AKCWallPaper#1]
The following are a couple of tasks.

- [ ] - Fix the wiki page
- [ ] - Search filter
- [ ] - Improve image transition
- [ ] - transition from tag from image click to search view
- [ ] - add option to search wiki page from clicking on search tag
