### ISSUE TITLE
UI Unit Testing TODO

### ISSUE THREAD

**Issue by voldien** [voldien/AKCWallPaper#2]
A list of task to be added in the UI test suite

- [ ] Scroll post view in portrait mode and transition to landscape mode
- [ ] Click  the first post image and display its information
- [ ] Click the first post image and click the first tag in the list
- [ ] Click the first post image - long click on the image and select wiki page.
- [ ] open preference view from post view, image view.
- [ ] swipe refresh
- [ ] scroll tag list to it reach the bottom and request the next page
- [ ] navigate history view
